[package]
name = "erosion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noise = "0.7.0"
rand = "0.8.5"
gdnative = "0.10.0"

[lib]
crate-type = ["cdylib"]